### ISSUE TITLE
about performance

### ISSUE THREAD

**Issue by zbw4034** [ZHANGHeng19931123/seq_nms_yolo#1]
Hello guys,glad to see your groups' wonderful work!
I have some questions about performance:
1.how about the detection speed(FPS)?
2.what's your working environment for your code?Can I run it on jetson TX2?

thank you~~

**Comment by ZHANGHeng19931123** [comment]
Hello, I'm working on GX 1080Ti. The Yolo runs at about 20 fps (on GPU) and seq-nms runs at about 17 fps (on CPU). So the final fps is around 9 fps.
